version: '3.7'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    depends_on:
      - postgres
    env_file:
      - ./app/cw.env
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=baltazarpost7623g
      - POSTGRES_USER=postgres
      - POSTGRES_DB=meme
      - POSTGRES_HOST=postgres
      # - POSTGRES_DB=Meme
      # ports:
      #   - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data
volumes:
  postgres-db:
