"""test auto mode

Revision ID: caab50a8c8bc
Revises: ab0fc233c89f
Create Date: 2023-05-27 18:19:45.171754

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'caab50a8c8bc'
down_revision = 'ab0fc233c89f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lol')
    op.drop_table('test_table')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_table',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('meme_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.NUMERIC(), server_default=sa.text("'1'::numeric"), autoincrement=False, nullable=True),
    sa.Column('num_of_grades', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('test_column', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='test_table_pkey')
    )
    op.create_table('lol',

    )
    # ### end Alembic commands ###
