name: build and deploy memeinator code

on:
  push:
    branches: ["master"]

jobs:
  memeinator:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repository
        uses: actions/checkout@v2
      - name: install Python 3.10.11
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.11"
