name: build and deploy memeinator code

on:
  push:
    branches: ["master"]

jobs:
  memeinator:
    env:
      IMAGGA_KEY: acc_69f61c59ee6cecd
      IMAGGA_SECRET: f948b6725ec1ac38f771b1ae383a3f78
      DB_HOST: localhost
      DB_NAME: meme
      DB_USER: postgres
      DB_PASS: baltazarpost7623g
      DB_PORT: 5432
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repository
        uses: actions/checkout@v3
      - name: install Python 3.10.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.11"
      - name: upgrade pip
        run: python -m pip install --upgrade pip
      - name: requirements
        run: pip install -r requirements.txt
      - name: pytest
        run: |
          pip install pytest
          ls
          pytest
